<?php

namespace Djunehor\EventRevert\Test;

use Djunehor\EventRevert\ModelLog;
use Djunehor\EventRevert\Test\Models\ModelEventLogTestUser;
use Faker\Factory;

class ModelEventLogRouteTest extends TestCase
{
    /* -----------------------------------------------------------------
     |  Tests
     | -----------------------------------------------------------------
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        auth()->loginUsingId(ModelEventLogTestUser::find(1)->id);
        $faker = Factory::create();
        for ($i = 0; $i < 5; $i++) {
            $this->model::create([
                'name' => $faker->name,
                'city' => $faker->city,
                'country' => $faker->country,
            ]);
        }
    }

    /** @test */
    public function it_can_access_model_event_log_list()
    {
        $response = $this->get('model-events');
        $response->assertSuccessful();
        $this->assertStringContainsString(trans('ModelEventLogger::model-event-logger.dashboard.title'), $response->getContent());
    }

    /** @test */
    public function it_can_access_model_event_log_list_by_model_log_id()
    {
        $faker = Factory::create();
        for ($i = 0; $i < 5; $i++) {
            $this->model::create([
                'name' => $faker->name,
                'city' => $faker->city,
                'country' => $faker->country,
            ]);
        }
        $response = $this->get('model-events/1');
        $response->assertSuccessful();
        $this->assertStringContainsString(trans('ModelEventLogger::model-event-logger.dashboard.title'), $response->getContent());
    }

    /** @test */
    public function it_can_revert_model_event()
    {
        $model = $this->create();
        $oldName = $model->name;
        $model->update(['name' => 'isabel']);

        $lastLog = ModelLog::query()->orderByDesc('id')->first();
        $response = $this->patch('model-event-revert/'.$lastLog->id);
        $response->assertSuccessful();
        $this->assertStringContainsString(trans('ModelEventLogger::model-event-logger.messages.logRevertedSuccessfully'), $response->getContent());
        $newModel = $this->model::find($model->id);
        $this->assertEquals($oldName, $newModel->name);
    }
}
